ALIVE_SERVICE=[
    'Alive and kicking',
    'Lock \'n loaded',
    'My life for DnD',
    'Stop poking me',
    'I like when you try to reach me',
    'I\'m alive, not by my choice',
    'What does "alive" means?',
    'I\'m alive, be grateful to Pelor',
    'Who\'s summoning me?',
    '(/^▽^)/',
    '(つ ͡° ͜ʖ ͡°)つ',
    '(╯°□°）╯︵ ┻━┻',
    'ಠ_ಠ'
]

EDGELORD_PARTS=[
    # Edgy antagonist
    [
        'An evil wizard',
        'A dragon',
        'The drow',
        'Goblins',
        'Kobolds',
        'A mind flayer',
        'Evil cultists',
        'Orcs',
        'Trolls',
        'A banshee',
        'A demon lord',
        'An archdevil',
        'Giants',
        'Vampires',
        'Gnolls',
        'A werefolf',
        'A Djinni',
        'A mimic',
        'A tarrasque',
        'A beholder',
        'A hag coven',
        'A lich',
        'Barbarians',
        'An aboleth',
        'A succubus',
        'A criminal organizations',
        'A gelatinous cube',
        'A necromancer',
        'Corrupt nobles',
        'A death knight',
        'The BBEG',
        'The bard',
        'Natural selection',
        'The DM',
    ],
    # Edgy action
    [
        'killed',
        'murdered',
        'slaughtered',
        'massacred',
        'assassinated',
        'brainwashed',
        'captured',
        'banished',
        'enslaved',
        'betrayed',
        'sacrificed',
        'mauled',
        'stole',
        'blackmailed',
        'conned',
        'framed',
        'humiliated',
        'pillaged',
        'ruined',
        'ate',
        'cursed',
        'befriended',
        'seduced'
    ],
    # Edgy victim
    [
        'my family',
        'my hometown',
        'my parents',
        'my clan',
        'my sibling',
        'my mentors',
        'my significant other',
        'my master',
        'my side squeeze',
        'my apprentice',
        'my friends',
        'my previous adventuring party',
        'everyone I knew',
        'my crew of sailors',
        'my crew of pirates',
        'my crew of noble outlaws',
        'my crew of thieves',
        'the tavern I basically lived in',
        'my military unit',
        'my social status',
        'my treasure',
        'my aspirations',
        'my honour',
        'my confidence',
        'my imaginary friends'
    ],
    #Edgy outcome
    [
        'and it will have no effect on how i roleplay my character',
        'and now I\'m a murder hobo',
        'and now I\'m a lawful good stick in the mud',
        'and now I seek vengeance',
        'and now I trust no one',
        'and now I have a bleak outlook of the world',
        'and now I strive to live by their ideals',
        'and now I must become stronger',
        'and now I seek to bring back what I have lost',
        'and now I vow to prevent that from happening to anyone else',
        'and now I am haunted by their memory',
        'and now I seek to uncover the truth about what happened',
        'and now I i fear it will happen again',
        'and now I am stronger because of it',
        'and now I\'m and alcoholic',
        'and now I have multiclassed into warlock',
        'and now I\'m Batman'
    ]
]